name: Bug Report
description: Report a bug
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Something isn't working
    validations:
      required: true