import {
  siArchlinux,
  siAstro,
  siDigitalocean,
  siDocker,
  siExpo,
  siExpress,
  siFastify,
  siFlydotio,
  siGit,
  siGithub,
  siGithubactions,
  siGnubash,
  siGo,
  siGooglemaps,
  siHyprland,
  siJavascript,
  siLinux,
  siLottiefiles,
  siLua,
  siMongodb,
  siNeovim,
  siNginx,
  siNodedotjs,
  siNpm,
  siPnpm,
  siPostgresql,
  siPrisma,
  siPython,
  siReact,
  siRedis,
  siTailwindcss,
  siTmux,
  siTypescript,
  siVercel,
  siVite,
  siZod,
} from 'simple-icons'

type StackIconData = {
  title: string
  path: string
}

export const stackIcons: Record<string, StackIconData> = {
  archlinux: siArchlinux,
  astro: siAstro,
  bash: siGnubash,
  digitalocean: siDigitalocean,
  docker: siDocker,
  expo: siExpo,
  express: siExpress,
  fastify: siFastify,
  flydotio: siFlydotio,
  git: siGit,
  github: siGithub,
  githubactions: siGithubactions,
  go: siGo,
  googlemaps: siGooglemaps,
  hyprland: siHyprland,
  javascript: siJavascript,
  linux: siLinux,
  lottie: siLottiefiles,
  lua: siLua,
  mongodb: siMongodb,
  neovim: siNeovim,
  nginx: siNginx,
  nodejs: siNodedotjs,
  npm: siNpm,
  pnpm: siPnpm,
  postgresql: siPostgresql,
  prisma: siPrisma,
  python: siPython,
  react: siReact,
  redis: siRedis,
  tailwind: siTailwindcss,
  tmux: siTmux,
  typescript: siTypescript,
  vercel: siVercel,
  vite: siVite,
  zod: siZod,
}
